version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contactos_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PGUSER: postgres
      PGHOST: db
      PGDATABASE: contactos_db
      PGPASSWORD: postgres
      PGPORT: 5432

volumes:
  pgdata:
